require("src.app.connect.Port")
require("src.app.connect.ConnectMgr")
require("src.base.BaseConfig")
require("src.base.BaseConnect")
require("src.command.type_collection")
require("src.base.tools.windowutils")
require("src.app.timer.ServerTimer")
require("src.command.resource")
require("src.app.data.Player")
require("src.command.command")
display.loadLanguage(require("src.base.tools.storage").getXML("language") or "sc")